# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ApiKeyKind,
        ApiKeyScope,
        ErrorCode,
        ErrorEnvelope,
        ErrorResponse,
        EstimateResponse,
        FileUploadResponse,
        HttpValidationError,
        KeyCreateResponse,
        KeyListResponse,
        KeyRotateResponse,
        KeyStatus,
        KeySummary,
        Metrics,
        ModelDetail,
        ModelListResponse,
        ModelRoute,
        ModelSummary,
        ModelVariant,
        OutputItem,
        RequestListResponse,
        RequestStatus,
        RequestSummary,
        ResultResponse,
        StatusLog,
        StatusResponse,
        SubmitResponse,
        TokenCreateResponse,
        ValidationError,
        ValidationErrorLocItem,
        VoiceListResponse,
        VoiceSummary,
        WebhookPublicKey,
    )
    from .errors import (
        BadRequestError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        TooManyRequestsError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
    from . import files, keys, models, queue, requests, tokens, webhooks
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncHedra, Hedra
    from .environment import HedraEnvironment
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "ApiKeyKind": ".types",
    "ApiKeyScope": ".types",
    "AsyncHedra": ".client",
    "BadRequestError": ".errors",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorCode": ".types",
    "ErrorEnvelope": ".types",
    "ErrorResponse": ".types",
    "EstimateResponse": ".types",
    "FileUploadResponse": ".types",
    "ForbiddenError": ".errors",
    "Hedra": ".client",
    "HedraEnvironment": ".environment",
    "HttpValidationError": ".types",
    "InternalServerError": ".errors",
    "KeyCreateResponse": ".types",
    "KeyListResponse": ".types",
    "KeyRotateResponse": ".types",
    "KeyStatus": ".types",
    "KeySummary": ".types",
    "Metrics": ".types",
    "ModelDetail": ".types",
    "ModelListResponse": ".types",
    "ModelRoute": ".types",
    "ModelSummary": ".types",
    "ModelVariant": ".types",
    "NotFoundError": ".errors",
    "OutputItem": ".types",
    "RequestListResponse": ".types",
    "RequestStatus": ".types",
    "RequestSummary": ".types",
    "ResultResponse": ".types",
    "StatusLog": ".types",
    "StatusResponse": ".types",
    "SubmitResponse": ".types",
    "TokenCreateResponse": ".types",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
    "VoiceListResponse": ".types",
    "VoiceSummary": ".types",
    "WebhookPublicKey": ".types",
    "__version__": ".version",
    "files": ".files",
    "keys": ".keys",
    "models": ".models",
    "queue": ".queue",
    "requests": ".requests",
    "tokens": ".tokens",
    "webhooks": ".webhooks",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiKeyKind",
    "ApiKeyScope",
    "AsyncHedra",
    "BadRequestError",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorCode",
    "ErrorEnvelope",
    "ErrorResponse",
    "EstimateResponse",
    "FileUploadResponse",
    "ForbiddenError",
    "Hedra",
    "HedraEnvironment",
    "HttpValidationError",
    "InternalServerError",
    "KeyCreateResponse",
    "KeyListResponse",
    "KeyRotateResponse",
    "KeyStatus",
    "KeySummary",
    "Metrics",
    "ModelDetail",
    "ModelListResponse",
    "ModelRoute",
    "ModelSummary",
    "ModelVariant",
    "NotFoundError",
    "OutputItem",
    "RequestListResponse",
    "RequestStatus",
    "RequestSummary",
    "ResultResponse",
    "StatusLog",
    "StatusResponse",
    "SubmitResponse",
    "TokenCreateResponse",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "ValidationError",
    "ValidationErrorLocItem",
    "VoiceListResponse",
    "VoiceSummary",
    "WebhookPublicKey",
    "__version__",
    "files",
    "keys",
    "models",
    "queue",
    "requests",
    "tokens",
    "webhooks",
]
