# This file was auto-generated by Fern from our API Definition.

import enum


class HedraEnvironment(enum.Enum):
    PRODUCTION = "https://api.hedra.com/v3"
    STAGING = "https://api.staging.hedra.com/v3"
