# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.open_ai_error_response import OpenAiErrorResponse


class BadGatewayError(ApiError):
    def __init__(self, body: OpenAiErrorResponse, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=502, headers=headers, body=body)
