# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_key_kind import ApiKeyKind
    from .api_key_scope import ApiKeyScope
    from .error_code import ErrorCode
    from .error_envelope import ErrorEnvelope
    from .error_response import ErrorResponse
    from .estimate_response import EstimateResponse
    from .file_upload_response import FileUploadResponse
    from .http_validation_error import HttpValidationError
    from .key_create_response import KeyCreateResponse
    from .key_list_response import KeyListResponse
    from .key_rotate_response import KeyRotateResponse
    from .key_status import KeyStatus
    from .key_summary import KeySummary
    from .metrics import Metrics
    from .model_detail import ModelDetail
    from .model_list_response import ModelListResponse
    from .model_route import ModelRoute
    from .model_summary import ModelSummary
    from .model_variant import ModelVariant
    from .output_item import OutputItem
    from .request_list_response import RequestListResponse
    from .request_status import RequestStatus
    from .request_summary import RequestSummary
    from .result_response import ResultResponse
    from .status_log import StatusLog
    from .status_response import StatusResponse
    from .submit_response import SubmitResponse
    from .token_create_response import TokenCreateResponse
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .voice_list_response import VoiceListResponse
    from .voice_summary import VoiceSummary
    from .webhook_public_key import WebhookPublicKey
_dynamic_imports: typing.Dict[str, str] = {
    "ApiKeyKind": ".api_key_kind",
    "ApiKeyScope": ".api_key_scope",
    "ErrorCode": ".error_code",
    "ErrorEnvelope": ".error_envelope",
    "ErrorResponse": ".error_response",
    "EstimateResponse": ".estimate_response",
    "FileUploadResponse": ".file_upload_response",
    "HttpValidationError": ".http_validation_error",
    "KeyCreateResponse": ".key_create_response",
    "KeyListResponse": ".key_list_response",
    "KeyRotateResponse": ".key_rotate_response",
    "KeyStatus": ".key_status",
    "KeySummary": ".key_summary",
    "Metrics": ".metrics",
    "ModelDetail": ".model_detail",
    "ModelListResponse": ".model_list_response",
    "ModelRoute": ".model_route",
    "ModelSummary": ".model_summary",
    "ModelVariant": ".model_variant",
    "OutputItem": ".output_item",
    "RequestListResponse": ".request_list_response",
    "RequestStatus": ".request_status",
    "RequestSummary": ".request_summary",
    "ResultResponse": ".result_response",
    "StatusLog": ".status_log",
    "StatusResponse": ".status_response",
    "SubmitResponse": ".submit_response",
    "TokenCreateResponse": ".token_create_response",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "VoiceListResponse": ".voice_list_response",
    "VoiceSummary": ".voice_summary",
    "WebhookPublicKey": ".webhook_public_key",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiKeyKind",
    "ApiKeyScope",
    "ErrorCode",
    "ErrorEnvelope",
    "ErrorResponse",
    "EstimateResponse",
    "FileUploadResponse",
    "HttpValidationError",
    "KeyCreateResponse",
    "KeyListResponse",
    "KeyRotateResponse",
    "KeyStatus",
    "KeySummary",
    "Metrics",
    "ModelDetail",
    "ModelListResponse",
    "ModelRoute",
    "ModelSummary",
    "ModelVariant",
    "OutputItem",
    "RequestListResponse",
    "RequestStatus",
    "RequestSummary",
    "ResultResponse",
    "StatusLog",
    "StatusResponse",
    "SubmitResponse",
    "TokenCreateResponse",
    "ValidationError",
    "ValidationErrorLocItem",
    "VoiceListResponse",
    "VoiceSummary",
    "WebhookPublicKey",
]
