# This file was auto-generated by Fern from our API Definition.

import typing

ApiKeyScope = typing.Union[
    typing.Literal[
        "generations:write",
        "requests:read",
        "models:read",
        "files:write",
        "webhooks:manage",
        "usage:read",
        "keys:manage",
    ],
    typing.Any,
]
