# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .asset_type import AssetType


class Asset(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The id of the asset.
    """

    type: AssetType = pydantic.Field()
    """
    The type of the asset.
    """

    name: str = pydantic.Field()
    """
    Name of the asset. Default to user-provided file name.
    """

    thumbnail_url: str = pydantic.Field()
    """
    URL of the thumbnail image.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional description of the asset.
    """

    is_favorite: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the asset is favorited by the user.
    """

    recent: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this asset was recently used by the user.
    """

    created_at: str = pydantic.Field()
    """
    Date the asset was created.
    """

    favorited_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    Date the asset was favorited.
    """

    asset: "AssetAsset" = pydantic.Field()
    """
    The asset itself.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .asset_asset import AssetAsset  # noqa: E402, I001
from .generated_video import GeneratedVideo  # noqa: E402, I001

update_forward_refs(Asset, AssetAsset=AssetAsset, GeneratedVideo=GeneratedVideo)
