# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BillingError(UniversalBaseModel):
    """
    Why a request was refused for funds, and what would clear it.

    The envelope's structured detail for `INSUFFICIENT_BALANCE`, the way
    `details` is its structured detail for a validation failure. Every amount is
    in `currency`, and `balance` is the same number `GET /balance` returns — so
    a client can decide whether to top up, wait, or fail over without a second
    round trip to work out which balance was short.
    """

    balance: float = pydantic.Field()
    """
    Spendable balance on the account this request bills, at the moment it was refused. The same value `GET /balance` returns.
    """

    required: typing.Optional[float] = pydantic.Field(default=None)
    """
    What this request needed. Null when the refusal is a funding precondition rather than a priced one — an upload is not priced, and some models cannot be quoted until their inputs are measured (`POST /models/{model}/estimate` says so explicitly).
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO-4217 code the amounts above are denominated in.
    """

    funding_url: str = pydantic.Field()
    """
    Where a human can add funds to the account this request bills. The API itself cannot add them.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
