# This file was auto-generated by Fern from our API Definition.

import typing

ErrorCode = typing.Union[
    typing.Literal[
        "UNKNOWN",
        "INVALID_ARGUMENT",
        "NOT_FOUND",
        "ALREADY_EXISTS",
        "ALREADY_IN_PROGRESS",
        "UNAUTHORIZED",
        "PERMISSION_DENIED",
        "MISSING_CREDITS",
        "MODERATION_FAILED",
        "FAILED_PRECONDITION",
        "DEADLINE_EXCEEDED",
        "RESOURCE_EXHAUSTED",
        "UNAVAILABLE",
        "INTERNAL",
    ],
    typing.Any,
]
