# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_envelope import ErrorEnvelope


class ErrorResponse(UniversalBaseModel):
    """
    Top-level error body: ``{"error": {...}}`` plus a debug id.
    """

    error: ErrorEnvelope
    trace_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Debug id to quote to support (32-char hex trace id), also emitted as the `X-Trace-Id` response header.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
