# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerationInputVeo31Video_Url(UniversalBaseModel):
    """
    Source video (video-to-video).
    """

    source: typing.Literal["url"] = "url"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GenerationInputVeo31Video_Asset(UniversalBaseModel):
    """
    Source video (video-to-video).
    """

    source: typing.Literal["asset"] = "asset"
    asset_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


GenerationInputVeo31Video = typing_extensions.Annotated[
    typing.Union[GenerationInputVeo31Video_Url, GenerationInputVeo31Video_Asset], pydantic.Field(discriminator="source")
]
