# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_gpt_image15aspect_ratio import GenerationInputGptImage15AspectRatio
from .generation_input_gpt_image15image import GenerationInputGptImage15Image
from .generation_input_gpt_image15resolution import GenerationInputGptImage15Resolution


class GenerationInputGptImage15(UniversalBaseModel):
    """
    Model-specific generation inputs for `gpt-image-15`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = None
    aspect_ratio: typing.Optional[GenerationInputGptImage15AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputGptImage15Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    image: typing.Optional[GenerationInputGptImage15Image] = pydantic.Field(default=None)
    """
    Source image (image-to-image).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
