# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_flux_kontext_pro_aspect_ratio import GenerationInputFluxKontextProAspectRatio
from .generation_input_flux_kontext_pro_image import GenerationInputFluxKontextProImage
from .generation_input_flux_kontext_pro_resolution import GenerationInputFluxKontextProResolution


class GenerationInputFluxKontextPro(UniversalBaseModel):
    """
    Model-specific generation inputs for `flux-kontext-pro`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = None
    aspect_ratio: typing.Optional[GenerationInputFluxKontextProAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputFluxKontextProResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    image: typing.Optional[GenerationInputFluxKontextProImage] = pydantic.Field(default=None)
    """
    Source image (image-to-image).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
