# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerateVideoUpscaleRequest(UniversalBaseModel):
    workspace_id: typing.Optional[str] = None
    agent_thread_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional agent thread ID to associate this generation with.
    """

    generation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead.
    """

    generation_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id.
    """

    ai_model_id: str = pydantic.Field()
    """
    The model to use for upscaling.
    """

    video_id: str = pydantic.Field()
    """
    The id of the Video asset to upscale.
    """

    upscale_factor: typing.Optional[float] = pydantic.Field(default=None)
    """
    Scale factor for upscaling (e.g., 1.5 for 1.5x, 2.0 for 2x). Default: 1.5
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
