# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_seedream45aspect_ratio import GenerationInputSeedream45AspectRatio
from .generation_input_seedream45image import GenerationInputSeedream45Image
from .generation_input_seedream45resolution import GenerationInputSeedream45Resolution


class GenerationInputSeedream45(UniversalBaseModel):
    """
    Model-specific generation inputs for `seedream-45`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = None
    aspect_ratio: typing.Optional[GenerationInputSeedream45AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputSeedream45Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    image: typing.Optional[GenerationInputSeedream45Image] = pydantic.Field(default=None)
    """
    Source image (image-to-image).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
