# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_grok_imagine_aspect_ratio import GenerationInputGrokImagineAspectRatio
from .generation_input_grok_imagine_image import GenerationInputGrokImagineImage


class GenerationInputGrokImagine(UniversalBaseModel):
    """
    Model-specific generation inputs for `grok-imagine`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = None
    aspect_ratio: typing.Optional[GenerationInputGrokImagineAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    image: typing.Optional[GenerationInputGrokImagineImage] = pydantic.Field(default=None)
    """
    Source image (image-to-image).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
