# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerationInputElevenlabsFlashMultilingualV2(UniversalBaseModel):
    """
    Model-specific generation inputs for `elevenlabs-flash-multilingual-v2`.
    """

    text: str = pydantic.Field()
    """
    Generation prompt.
    """

    stability: typing.Optional[float] = None
    speed: typing.Optional[float] = None
    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code; 'auto' by default.
    """

    voice_id: str = pydantic.Field()
    """
    Voice to speak with. List valid voices at GET /v3/models/elevenlabs-flash-multilingual-v2/voices.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
