# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerateImageRequest(UniversalBaseModel):
    workspace_id: typing.Optional[str] = None
    agent_thread_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional agent thread ID to associate this generation with.
    """

    generation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead.
    """

    generation_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id.
    """

    text_prompt: str = pydantic.Field()
    """
    The text prompt for image generation or image editing.
    """

    aspect_ratio: typing.Optional[str] = pydantic.Field(default=None)
    """
    The aspect ratio to use.
    """

    resolution: typing.Optional[str] = pydantic.Field(default=None)
    """
    The resolution to use formatted like '540p', '1080p', '1440p (2K QHD)', etc.
    """

    start_keyframe_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The id of the Image asset to use as the start keyframe. This will be ignored if reference_image_ids is provided.
    """

    ai_model_id: str = pydantic.Field()
    """
    The model to use.
    """

    reference_image_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The id(s) of the image(s) to reference in the generation. This is only used for image-to-image generation and will supersede start_keyframe_id.
    """

    batch_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of image variations to generate (1-8). When > 1, batch_results will contain all generation results.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, automatically enhance the prompt before generation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
