# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_grok_video_aspect_ratio import GenerationInputGrokVideoAspectRatio
from .generation_input_grok_video_image import GenerationInputGrokVideoImage
from .generation_input_grok_video_resolution import GenerationInputGrokVideoResolution


class GenerationInputGrokVideo(UniversalBaseModel):
    """
    Model-specific generation inputs for `grok-video`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputGrokVideoAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputGrokVideoResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: typing.Optional[GenerationInputGrokVideoImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
