# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_hedra_omnia_aspect_ratio import GenerationInputHedraOmniaAspectRatio
from .generation_input_hedra_omnia_audio import GenerationInputHedraOmniaAudio
from .generation_input_hedra_omnia_image import GenerationInputHedraOmniaImage
from .generation_input_hedra_omnia_resolution import GenerationInputHedraOmniaResolution


class GenerationInputHedraOmnia(UniversalBaseModel):
    """
    Model-specific generation inputs for `hedra-omnia`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputHedraOmniaAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputHedraOmniaResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: GenerationInputHedraOmniaImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: GenerationInputHedraOmniaAudio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
