# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerationInputHedraOmniaAudio_Url(UniversalBaseModel):
    """
    Driving audio.
    """

    source: typing.Literal["url"] = "url"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GenerationInputHedraOmniaAudio_Asset(UniversalBaseModel):
    """
    Driving audio.
    """

    source: typing.Literal["asset"] = "asset"
    asset_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


GenerationInputHedraOmniaAudio = typing_extensions.Annotated[
    typing.Union[GenerationInputHedraOmniaAudio_Url, GenerationInputHedraOmniaAudio_Asset],
    pydantic.Field(discriminator="source"),
]
