# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .asset_type import AssetType
from .generation_error import GenerationError
from .generation_input import GenerationInput
from .generation_status import GenerationStatus


class Generation(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    ID of the generation and associated asset.
    """

    type: AssetType = pydantic.Field()
    """
    Type of generation.
    """

    input: GenerationInput = pydantic.Field()
    """
    Inputs for the generation
    """

    status: GenerationStatus = pydantic.Field()
    """
    Status of the generation
    """

    progress: float = pydantic.Field()
    """
    Current progress to completion. Between 0-1
    """

    eta_sec: typing.Optional[int] = pydantic.Field(default=None)
    """
    Estimated time remaining in seconds until generation completes.
    """

    created_at: str = pydantic.Field()
    """
    Date the generation was submitted.
    """

    credit_cost: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits consumed (debits) for this generation.
    """

    batch_generation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier linking all generations in a batch.
    """

    asset: typing.Optional["Asset"] = pydantic.Field(default=None)
    """
    The generated asset. Value is not present unless the status of the generation is 'complete'
    """

    error: typing.Optional[GenerationError] = pydantic.Field(default=None)
    """
    Generation error if any. Value is not present unless the status of the generation is 'error' and error_message field is not present.
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message. Value is not present unless the status of the generation is 'error' and error field is not present.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .asset import Asset  # noqa: E402, I001
from .asset_asset import AssetAsset  # noqa: E402, I001
from .generated_video import GeneratedVideo  # noqa: E402, I001

update_forward_refs(Generation, Asset=Asset, AssetAsset=AssetAsset, GeneratedVideo=GeneratedVideo)
