# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerateAudioFromVideoRequest(UniversalBaseModel):
    """
    Audio generation request that extracts sound effects from video using Mirelo Studio.
    """

    workspace_id: typing.Optional[str] = None
    agent_thread_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional agent thread ID to associate this generation with.
    """

    generation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead.
    """

    generation_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id.
    """

    audio_generation_model_id: str = pydantic.Field()
    """
    ID of the model to use for video-to-audio generation (Mirelo Studio).
    """

    video_id: str = pydantic.Field()
    """
    The id of the video asset to generate audio from.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional prompt to guide the audio generation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
