# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_veed_fabric10aspect_ratio import GenerationInputVeedFabric10AspectRatio
from .generation_input_veed_fabric10audio import GenerationInputVeedFabric10Audio
from .generation_input_veed_fabric10image import GenerationInputVeedFabric10Image
from .generation_input_veed_fabric10resolution import GenerationInputVeedFabric10Resolution


class GenerationInputVeedFabric10(UniversalBaseModel):
    """
    Model-specific generation inputs for `veed-fabric-10`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputVeedFabric10AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputVeedFabric10Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: GenerationInputVeedFabric10Image = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: GenerationInputVeedFabric10Audio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
