# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_veo31fast_aspect_ratio import GenerationInputVeo31FastAspectRatio
from .generation_input_veo31fast_end_image import GenerationInputVeo31FastEndImage
from .generation_input_veo31fast_image import GenerationInputVeo31FastImage
from .generation_input_veo31fast_resolution import GenerationInputVeo31FastResolution
from .generation_input_veo31fast_video import GenerationInputVeo31FastVideo


class GenerationInputVeo31Fast(UniversalBaseModel):
    """
    Model-specific generation inputs for `veo-31-fast`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputVeo31FastAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputVeo31FastResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: typing.Optional[GenerationInputVeo31FastImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[GenerationInputVeo31FastEndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    video: typing.Optional[GenerationInputVeo31FastVideo] = pydantic.Field(default=None)
    """
    Source video (video-to-video).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
