# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_kling21pro_aspect_ratio import GenerationInputKling21ProAspectRatio
from .generation_input_kling21pro_image import GenerationInputKling21ProImage
from .generation_input_kling21pro_resolution import GenerationInputKling21ProResolution


class GenerationInputKling21Pro(UniversalBaseModel):
    """
    Model-specific generation inputs for `kling-21-pro`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputKling21ProAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputKling21ProResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: typing.Optional[GenerationInputKling21ProImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
