# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_minimax_hailuo23standard_aspect_ratio import GenerationInputMinimaxHailuo23StandardAspectRatio
from .generation_input_minimax_hailuo23standard_image import GenerationInputMinimaxHailuo23StandardImage
from .generation_input_minimax_hailuo23standard_resolution import GenerationInputMinimaxHailuo23StandardResolution


class GenerationInputMinimaxHailuo23Standard(UniversalBaseModel):
    """
    Model-specific generation inputs for `minimax-hailuo-23-standard`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputMinimaxHailuo23StandardAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputMinimaxHailuo23StandardResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: typing.Optional[GenerationInputMinimaxHailuo23StandardImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
