# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generated_audio_inputs import GeneratedAudioInputs


class GeneratedAudio(UniversalBaseModel):
    duration_ms: int = pydantic.Field()
    """
    Duration of the audio in seconds.
    """

    url: str = pydantic.Field()
    """
    URL of the audio.
    """

    generated_audio_inputs: GeneratedAudioInputs = pydantic.Field()
    """
    Inputs for generating the audio.
    """

    transcriptions: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Transcriptions of the audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
