# This file was auto-generated by Fern from our API Definition.

import typing

GenerationInputSeedream40Resolution = typing.Union[
    typing.Literal["1080p", "1440p (2K QHD)", "2160p (4K UHD)"], typing.Any
]
