# This file was auto-generated by Fern from our API Definition.

import typing

GenerationInputNanoBananaAspectRatio = typing.Union[
    typing.Literal["16:9", "9:16", "1:1", "21:9", "4:3", "3:2", "2:3", "5:4", "4:5", "3:4"], typing.Any
]
