# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .generated_video_inputs import GeneratedVideoInputs


class GeneratedVideo(UniversalBaseModel):
    width: int = pydantic.Field()
    """
    Width of the image.
    """

    height: int = pydantic.Field()
    """
    Height of the image.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the image.
    """

    download_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to download the video
    """

    streaming_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to stream the video
    """

    poster_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the poster image
    """

    duration_ms: int = pydantic.Field()
    """
    Duration of the video.
    """

    preview_url: str = pydantic.Field()
    """
    URL of the preview for animated thumbnails.
    """

    generated_video_inputs: GeneratedVideoInputs = pydantic.Field()
    """
    Inputs for generating the video.
    """

    keyframe_start: typing.Optional["Asset"] = pydantic.Field(default=None)
    """
    URL of the Image asset used as the start keyframe.
    """

    keyframe_end: typing.Optional["Asset"] = pydantic.Field(default=None)
    """
    URL of the Image asset used as the end keyframe.
    """

    audio: typing.Optional["Asset"] = pydantic.Field(default=None)
    """
    URL of the Audio asset used as the basis for the video.
    """

    reference_image_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The id(s) of the image(s) referenced in the generation.
    """

    source_video_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The id of the Video asset used as source input for motion control/video-to-video generation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .asset import Asset  # noqa: E402, I001
from .asset_asset import AssetAsset  # noqa: E402, I001

update_forward_refs(GeneratedVideo, Asset=Asset, AssetAsset=AssetAsset)
