# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_hedra_avatar_aspect_ratio import GenerationInputHedraAvatarAspectRatio
from .generation_input_hedra_avatar_audio import GenerationInputHedraAvatarAudio
from .generation_input_hedra_avatar_image import GenerationInputHedraAvatarImage
from .generation_input_hedra_avatar_resolution import GenerationInputHedraAvatarResolution


class GenerationInputHedraAvatar(UniversalBaseModel):
    """
    Model-specific generation inputs for `hedra-avatar`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputHedraAvatarAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputHedraAvatarResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: GenerationInputHedraAvatarImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: GenerationInputHedraAvatarAudio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
