# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_gpt_image2medium_aspect_ratio import GenerationInputGptImage2MediumAspectRatio
from .generation_input_gpt_image2medium_image import GenerationInputGptImage2MediumImage
from .generation_input_gpt_image2medium_resolution import GenerationInputGptImage2MediumResolution


class GenerationInputGptImage2Medium(UniversalBaseModel):
    """
    Model-specific generation inputs for `gpt-image-2-medium`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = None
    aspect_ratio: typing.Optional[GenerationInputGptImage2MediumAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputGptImage2MediumResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    image: typing.Optional[GenerationInputGptImage2MediumImage] = pydantic.Field(default=None)
    """
    Source image (image-to-image).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
