# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_minimax_hailuo23fast_pro_aspect_ratio import GenerationInputMinimaxHailuo23FastProAspectRatio
from .generation_input_minimax_hailuo23fast_pro_image import GenerationInputMinimaxHailuo23FastProImage
from .generation_input_minimax_hailuo23fast_pro_resolution import GenerationInputMinimaxHailuo23FastProResolution


class GenerationInputMinimaxHailuo23FastPro(UniversalBaseModel):
    """
    Model-specific generation inputs for `minimax-hailuo-23-fast-pro`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputMinimaxHailuo23FastProAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputMinimaxHailuo23FastProResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: GenerationInputMinimaxHailuo23FastProImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
