# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_kling_o1aspect_ratio import GenerationInputKlingO1AspectRatio
from .generation_input_kling_o1end_image import GenerationInputKlingO1EndImage
from .generation_input_kling_o1image import GenerationInputKlingO1Image
from .generation_input_kling_o1images_item import GenerationInputKlingO1ImagesItem
from .generation_input_kling_o1resolution import GenerationInputKlingO1Resolution


class GenerationInputKlingO1(UniversalBaseModel):
    """
    Model-specific generation inputs for `kling-o1`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputKlingO1AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputKlingO1Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: typing.Optional[GenerationInputKlingO1Image] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[GenerationInputKlingO1EndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    images: typing.Optional[typing.List[GenerationInputKlingO1ImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
