# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerationInputNanoBanana2Image_Url(UniversalBaseModel):
    """
    Source image (image-to-image); omit for text-to-image.
    """

    source: typing.Literal["url"] = "url"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GenerationInputNanoBanana2Image_Asset(UniversalBaseModel):
    """
    Source image (image-to-image); omit for text-to-image.
    """

    source: typing.Literal["asset"] = "asset"
    asset_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


GenerationInputNanoBanana2Image = typing_extensions.Annotated[
    typing.Union[GenerationInputNanoBanana2Image_Url, GenerationInputNanoBanana2Image_Asset],
    pydantic.Field(discriminator="source"),
]
