# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generated_video_inputs_character_orientation import GeneratedVideoInputsCharacterOrientation
from .normalized_point import NormalizedPoint


class GeneratedVideoInputs(UniversalBaseModel):
    text_prompt: str = pydantic.Field()
    """
    Prompt for video generation.
    """

    ai_model_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The id of the model used for generation.
    """

    resolution: typing.Optional[str] = pydantic.Field(default=None)
    """
    Resolution for the video.
    """

    aspect_ratio: typing.Optional[str] = pydantic.Field(default=None)
    """
    Aspect ratio for the video.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration of the video in milliseconds.
    """

    bounding_box_target: typing.Optional[NormalizedPoint] = pydantic.Field(default=None)
    """
    Normalized coordinates for primary speaker position (Character3 only)
    """

    character_orientation: typing.Optional[GeneratedVideoInputsCharacterOrientation] = pydantic.Field(default=None)
    """
    For motion control models: 'video' matches reference video orientation (better for complex motions, max 30s), 'image' preserves character image orientation (better for camera movements, max 10s).
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, automatically enhance the prompt before generation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
