# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_imagen4aspect_ratio import GenerationInputImagen4AspectRatio
from .generation_input_imagen4resolution import GenerationInputImagen4Resolution


class GenerationInputImagen4(UniversalBaseModel):
    """
    Model-specific generation inputs for `imagen4`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = None
    aspect_ratio: typing.Optional[GenerationInputImagen4AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputImagen4Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
