# This file was auto-generated by Fern from our API Definition.

import typing

GenerationInputRecraftV3AspectRatio = typing.Union[
    typing.Literal["16:9", "9:16", "1:1", "4:3", "3:4", "16:10", "10:16", "3:2", "2:3", "3:1", "1:3"], typing.Any
]
