# This file was auto-generated by Fern from our API Definition.

import typing

GenerationErrorType = typing.Union[
    typing.Literal[
        "UNKNOWN", "MODERATION_FAILED", "MISSING_CREDITS", "RESOURCE_EXHAUSTED", "INVALID_ARGUMENT", "UNAVAILABLE"
    ],
    typing.Any,
]
