# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_status import GenerationStatus


class GenerateVoiceCloneResponse(UniversalBaseModel):
    workspace_id: typing.Optional[str] = None
    agent_thread_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional agent thread ID to associate this generation with.
    """

    generation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional pre-reserved generation ID. If provided, this ID will be used instead of generating a new one. For batch operations (batch_size > 1), use generation_ids instead.
    """

    generation_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional list of pre-reserved generation IDs for batch operations. Length must match batch_size. Mutually exclusive with generation_id.
    """

    audio_id: str = pydantic.Field()
    """
    The id of the Audio asset to use as the basis for the clone.
    """

    name: str = pydantic.Field()
    """
    The name of the new voice. Required by ElevenLabs to create a new voice.
    """

    id: str = pydantic.Field()
    """
    The id of the generation. Can be used to check status.
    """

    asset_id: str = pydantic.Field()
    """
    The id of the resulting Voice asset.
    """

    created_at: str = pydantic.Field()
    """
    Date the generation was submitted.
    """

    status: GenerationStatus = pydantic.Field()
    """
    Status of the generation
    """

    progress: float = pydantic.Field()
    """
    Current progress to completion. Between 0-1
    """

    eta_sec: typing.Optional[int] = pydantic.Field(default=None)
    """
    Estimated time until completion in seconds. May be None if no historical data available.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
