# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_kling_o3pro_aspect_ratio import GenerationInputKlingO3ProAspectRatio
from .generation_input_kling_o3pro_end_image import GenerationInputKlingO3ProEndImage
from .generation_input_kling_o3pro_image import GenerationInputKlingO3ProImage
from .generation_input_kling_o3pro_images_item import GenerationInputKlingO3ProImagesItem
from .generation_input_kling_o3pro_resolution import GenerationInputKlingO3ProResolution


class GenerationInputKlingO3Pro(UniversalBaseModel):
    """
    Model-specific generation inputs for `kling-o3-pro`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputKlingO3ProAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputKlingO3ProResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: typing.Optional[GenerationInputKlingO3ProImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[GenerationInputKlingO3ProEndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    images: typing.Optional[typing.List[GenerationInputKlingO3ProImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
