# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_veed_fabric10fast_aspect_ratio import GenerationInputVeedFabric10FastAspectRatio
from .generation_input_veed_fabric10fast_audio import GenerationInputVeedFabric10FastAudio
from .generation_input_veed_fabric10fast_image import GenerationInputVeedFabric10FastImage
from .generation_input_veed_fabric10fast_resolution import GenerationInputVeedFabric10FastResolution


class GenerationInputVeedFabric10Fast(UniversalBaseModel):
    """
    Model-specific generation inputs for `veed-fabric-10-fast`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputVeedFabric10FastAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputVeedFabric10FastResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: GenerationInputVeedFabric10FastImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: GenerationInputVeedFabric10FastAudio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
