# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_input_kling_ai_avatar_v2standard_aspect_ratio import GenerationInputKlingAiAvatarV2StandardAspectRatio
from .generation_input_kling_ai_avatar_v2standard_audio import GenerationInputKlingAiAvatarV2StandardAudio
from .generation_input_kling_ai_avatar_v2standard_image import GenerationInputKlingAiAvatarV2StandardImage
from .generation_input_kling_ai_avatar_v2standard_resolution import GenerationInputKlingAiAvatarV2StandardResolution


class GenerationInputKlingAiAvatarV2Standard(UniversalBaseModel):
    """
    Model-specific generation inputs for `kling-ai-avatar-v2-standard`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    aspect_ratio: typing.Optional[GenerationInputKlingAiAvatarV2StandardAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[GenerationInputKlingAiAvatarV2StandardResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    image: GenerationInputKlingAiAvatarV2StandardImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: GenerationInputKlingAiAvatarV2StandardAudio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
