# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeneratedAudioInputs(UniversalBaseModel):
    text_prompt: str = pydantic.Field()
    """
    Prompt for audio generation.
    """

    ai_model_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The id of the model used for generation.
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The id of the voice used for generation.
    """

    stability: typing.Optional[float] = pydantic.Field(default=None)
    """
    Stability setting used for generation (0-1).
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed setting used for generation (0.7-1.2).
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language used for generation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
