# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generated_image_inputs import GeneratedImageInputs


class GeneratedImage(UniversalBaseModel):
    width: int = pydantic.Field()
    """
    Width of the image.
    """

    height: int = pydantic.Field()
    """
    Height of the image.
    """

    url: str = pydantic.Field()
    """
    URL of the image.
    """

    generated_image_inputs: GeneratedImageInputs = pydantic.Field()
    """
    Inputs for generating the image.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
