# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_pixverse_v6aspect_ratio import InputPixverseV6AspectRatio
from .input_pixverse_v6resolution import InputPixverseV6Resolution
from .input_pixverse_v6start_image import InputPixverseV6StartImage


class InputPixverseV6(UniversalBaseModel):
    """
    Model-specific inputs for `pixverse-v6`.

    Accepted field combinations (one per input mode):
    (1) requires: duration_ms, prompt, resolution, start_image; must omit: aspect_ratio
    (2) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: start_image
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    resolution: InputPixverseV6Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    generate_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to generate native audio for the video.
    """

    negative_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    What to avoid in the generated video.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    start_image: typing.Optional[InputPixverseV6StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    aspect_ratio: typing.Optional[InputPixverseV6AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
