# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_seedream45aspect_ratio import InputSeedream45AspectRatio
from .input_seedream45images_item import InputSeedream45ImagesItem
from .input_seedream45resolution import InputSeedream45Resolution


class InputSeedream45(UniversalBaseModel):
    """
    Model-specific inputs for `seedream-45`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputSeedream45AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputSeedream45Resolution = pydantic.Field()
    """
    Output resolution.
    """

    images: typing.Optional[typing.List[InputSeedream45ImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
