# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_kling_v3aspect_ratio import InputKlingV3AspectRatio
from .input_kling_v3end_image import InputKlingV3EndImage
from .input_kling_v3multi_prompt_item import InputKlingV3MultiPromptItem
from .input_kling_v3quality import InputKlingV3Quality
from .input_kling_v3resolution import InputKlingV3Resolution
from .input_kling_v3shot_type import InputKlingV3ShotType
from .input_kling_v3start_image import InputKlingV3StartImage


class InputKlingV3(UniversalBaseModel):
    """
    Model-specific inputs for `kling-v3`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, resolution, start_image; must omit: end_image; accepts quality: pro; resolution: 1080p | 4K
    (2) requires: aspect_ratio, duration_ms, end_image, resolution, start_image; accepts quality: pro; resolution: 1080p | 4K
    (3) requires: aspect_ratio, duration_ms, resolution; must omit: end_image, start_image; accepts quality: pro; resolution: 1080p | 4K
    (4) requires: aspect_ratio, duration_ms, start_image; must omit: end_image; accepts quality: standard; resolution: 720p
    (5) requires: aspect_ratio, duration_ms, end_image, start_image; accepts quality: standard; resolution: 720p
    (6) requires: aspect_ratio, duration_ms; must omit: end_image, start_image; accepts quality: standard; resolution: 720p
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generation prompt. At most 2500 characters.
    """

    multi_prompt: typing.Optional[typing.List[InputKlingV3MultiPromptItem]] = pydantic.Field(default=None)
    """
    Multi-shot storyboard; each shot carries its own prompt and duration. Shot durations must sum to at most 15000 ms, and the storyboard replaces `prompt` — supply one or the other, never both. A shot's prompt has no length limit, unlike the single `prompt` field. 1 to 6 items.
    """

    shot_type: typing.Optional[InputKlingV3ShotType] = pydantic.Field(default=None)
    """
    How a multi-shot storyboard is cut. 'customize' honours each shot's declared duration; 'intelligent' lets the model determine the shot structure. Ignored unless `multi_prompt` is supplied.
    """

    generate_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to generate native audio for the video.
    """

    negative_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    What to avoid in the generated video. At most 2500 characters.
    """

    aspect_ratio: InputKlingV3AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputKlingV3Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputKlingV3StartImage] = pydantic.Field(default=None)
    """
    Start frame. At most 10.4 MB.
    """

    cfg_scale: typing.Optional[float] = pydantic.Field(default=None)
    """
    How closely the model follows the prompt. From 0 to 1.
    """

    end_image: typing.Optional[InputKlingV3EndImage] = pydantic.Field(default=None)
    """
    End frame. At most 10.4 MB.
    """

    quality: typing.Optional[InputKlingV3Quality] = pydantic.Field(default=None)
    """
    Quality level to generate at. `standard` — the 720p tier. `pro` — the high-resolution tier, at 1080p and 4K.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
