# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_kling_ai_avatar_v2aspect_ratio import InputKlingAiAvatarV2AspectRatio
from .input_kling_ai_avatar_v2audio import InputKlingAiAvatarV2Audio
from .input_kling_ai_avatar_v2quality import InputKlingAiAvatarV2Quality
from .input_kling_ai_avatar_v2resolution import InputKlingAiAvatarV2Resolution
from .input_kling_ai_avatar_v2start_image import InputKlingAiAvatarV2StartImage


class InputKlingAiAvatarV2(UniversalBaseModel):
    """
    Model-specific inputs for `kling-ai-avatar-v2`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generation prompt.
    """

    aspect_ratio: InputKlingAiAvatarV2AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputKlingAiAvatarV2Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    start_image: InputKlingAiAvatarV2StartImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: InputKlingAiAvatarV2Audio = pydantic.Field()
    """
    Driving audio.
    """

    quality: InputKlingAiAvatarV2Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
