# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InputSeedance20StartImage_Url(UniversalBaseModel):
    """
    Start frame (image-to-video). With an aspect ratio from 0.4 to 2.5 and at most 30 MB.
    """

    source: typing.Literal["url"] = "url"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class InputSeedance20StartImage_Asset(UniversalBaseModel):
    """
    Start frame (image-to-video). With an aspect ratio from 0.4 to 2.5 and at most 30 MB.
    """

    source: typing.Literal["asset"] = "asset"
    asset_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


InputSeedance20StartImage = typing_extensions.Annotated[
    typing.Union[InputSeedance20StartImage_Url, InputSeedance20StartImage_Asset], pydantic.Field(discriminator="source")
]
