# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_veo3aspect_ratio import InputVeo3AspectRatio
from .input_veo3quality import InputVeo3Quality
from .input_veo3resolution import InputVeo3Resolution
from .input_veo3start_image import InputVeo3StartImage


class InputVeo3(UniversalBaseModel):
    """
    Model-specific inputs for `veo-3`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputVeo3AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputVeo3Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    generate_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to generate native audio for the video.
    """

    start_image: typing.Optional[InputVeo3StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    negative_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    What to avoid in the generated video.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    quality: InputVeo3Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
