# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_topaz_image_upscaler_wonder_enhancement_strength import InputTopazImageUpscalerWonderEnhancementStrength
from .input_topaz_image_upscaler_wonder_source_image import InputTopazImageUpscalerWonderSourceImage
from .input_topaz_image_upscaler_wonder_target_resolution import InputTopazImageUpscalerWonderTargetResolution


class InputTopazImageUpscalerWonder(UniversalBaseModel):
    """
    Model-specific inputs for `topaz-image-upscaler-wonder`.
    """

    source_image: InputTopazImageUpscalerWonderSourceImage = pydantic.Field()
    """
    The image to upscale. At most 30 MB.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    target_resolution: InputTopazImageUpscalerWonderTargetResolution = pydantic.Field()
    """
    Short edge of the upscaled image. The long edge follows the source's aspect ratio.
    """

    enhancement_strength: typing.Optional[InputTopazImageUpscalerWonderEnhancementStrength] = pydantic.Field(
        default=None
    )
    """
    How far the generative pass may depart from the source. Lower values stay closer to the original pixels; higher values invent more detail.
    """

    film_grain: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Add film grain to the upscaled image, which hides the over-smooth look generative upscaling can leave.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
