# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_kling16aspect_ratio import InputKling16AspectRatio
from .input_kling16resolution import InputKling16Resolution
from .input_kling16start_image import InputKling16StartImage


class InputKling16(UniversalBaseModel):
    """
    Model-specific inputs for `kling-16`.

    Accepted field combinations (one per input mode):
    (1) requires: prompt, start_image; accepts resolution: 1080p
    (2) requires: prompt; must omit: start_image; accepts resolution: 720p
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: typing.Optional[InputKling16AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputKling16Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputKling16StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    negative_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    What to avoid in the generated video.
    """

    cfg_scale: typing.Optional[float] = pydantic.Field(default=None)
    """
    How closely the model follows the prompt.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
