# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_hedra_avatar_aspect_ratio import InputHedraAvatarAspectRatio
from .input_hedra_avatar_audio import InputHedraAvatarAudio
from .input_hedra_avatar_resolution import InputHedraAvatarResolution
from .input_hedra_avatar_start_image import InputHedraAvatarStartImage


class InputHedraAvatar(UniversalBaseModel):
    """
    Model-specific inputs for `hedra-avatar`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputHedraAvatarAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputHedraAvatarResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    start_image: InputHedraAvatarStartImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: InputHedraAvatarAudio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
