# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_luma_ray32aspect_ratio import InputLumaRay32AspectRatio
from .input_luma_ray32resolution import InputLumaRay32Resolution


class InputLumaRay32(UniversalBaseModel):
    """
    Model-specific inputs for `luma-ray-32`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputLumaRay32AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputLumaRay32Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
