# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_sora2pro_aspect_ratio import InputSora2ProAspectRatio
from .input_sora2pro_resolution import InputSora2ProResolution
from .input_sora2pro_start_image import InputSora2ProStartImage


class InputSora2Pro(UniversalBaseModel):
    """
    Model-specific inputs for `sora-2-pro`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, prompt, resolution, start_image
    (2) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: start_image
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At most 5000 characters.
    """

    aspect_ratio: InputSora2ProAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputSora2ProResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputSora2ProStartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video). At most 10.4 MB.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
