# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_ltx23aspect_ratio import InputLtx23AspectRatio
from .input_ltx23end_image import InputLtx23EndImage
from .input_ltx23quality import InputLtx23Quality
from .input_ltx23resolution import InputLtx23Resolution
from .input_ltx23start_image import InputLtx23StartImage


class InputLtx23(UniversalBaseModel):
    """
    Model-specific inputs for `ltx-2-3`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    resolution: InputLtx23Resolution = pydantic.Field()
    """
    Output resolution.
    """

    generate_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to generate native audio for the video.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    aspect_ratio: InputLtx23AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    start_image: typing.Optional[InputLtx23StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[InputLtx23EndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    quality: InputLtx23Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
