# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_flux11ultra_aspect_ratio import InputFlux11UltraAspectRatio
from .input_flux11ultra_output_format import InputFlux11UltraOutputFormat
from .input_flux11ultra_resolution import InputFlux11UltraResolution


class InputFlux11Ultra(UniversalBaseModel):
    """
    Model-specific inputs for `flux-11-ultra`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputFlux11UltraAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputFlux11UltraResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    output_format: typing.Optional[InputFlux11UltraOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
