# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_seedance20aspect_ratio import InputSeedance20AspectRatio
from .input_seedance20audios_item import InputSeedance20AudiosItem
from .input_seedance20end_image import InputSeedance20EndImage
from .input_seedance20images_item import InputSeedance20ImagesItem
from .input_seedance20quality import InputSeedance20Quality
from .input_seedance20resolution import InputSeedance20Resolution
from .input_seedance20start_image import InputSeedance20StartImage
from .input_seedance20videos_item import InputSeedance20VideosItem


class InputSeedance20(UniversalBaseModel):
    """
    Model-specific inputs for `seedance-20`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, prompt, resolution; accepts quality: standard
    (2) requires: aspect_ratio, duration_ms, prompt, resolution; accepts quality: fast; resolution: 480p | 720p
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputSeedance20AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputSeedance20Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    generate_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to generate native audio for the video.
    """

    start_image: typing.Optional[InputSeedance20StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[InputSeedance20EndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    images: typing.Optional[typing.List[InputSeedance20ImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    videos: typing.Optional[typing.List[InputSeedance20VideosItem]] = pydantic.Field(default=None)
    """
    Reference videos.
    """

    audios: typing.Optional[typing.List[InputSeedance20AudiosItem]] = pydantic.Field(default=None)
    """
    Reference audios.
    """

    quality: InputSeedance20Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
