# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_flux_kontext_max_aspect_ratio import InputFluxKontextMaxAspectRatio
from .input_flux_kontext_max_images_item import InputFluxKontextMaxImagesItem
from .input_flux_kontext_max_output_format import InputFluxKontextMaxOutputFormat
from .input_flux_kontext_max_resolution import InputFluxKontextMaxResolution


class InputFluxKontextMax(UniversalBaseModel):
    """
    Model-specific inputs for `flux-kontext-max`.

    Accepted field combinations (one per input mode):
    (1) requires: images, prompt; must omit: aspect_ratio, resolution
    (2) requires: aspect_ratio, prompt; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    images: typing.Optional[typing.List[InputFluxKontextMaxImagesItem]] = pydantic.Field(default=None)
    """
    The single source image to edit.
    """

    output_format: typing.Optional[InputFluxKontextMaxOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    aspect_ratio: typing.Optional[InputFluxKontextMaxAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputFluxKontextMaxResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
