# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_gemini_omni_flash_aspect_ratio import InputGeminiOmniFlashAspectRatio
from .input_gemini_omni_flash_images_item import InputGeminiOmniFlashImagesItem
from .input_gemini_omni_flash_resolution import InputGeminiOmniFlashResolution
from .input_gemini_omni_flash_source_video import InputGeminiOmniFlashSourceVideo
from .input_gemini_omni_flash_start_image import InputGeminiOmniFlashStartImage
from .input_gemini_omni_flash_videos_item import InputGeminiOmniFlashVideosItem


class InputGeminiOmniFlash(UniversalBaseModel):
    """
    Model-specific inputs for `gemini-omni-flash`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputGeminiOmniFlashAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputGeminiOmniFlashResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputGeminiOmniFlashStartImage] = pydantic.Field(default=None)
    """
    Start frame. At most 10.4 MB.
    """

    source_video: typing.Optional[InputGeminiOmniFlashSourceVideo] = pydantic.Field(default=None)
    """
    Source video. From 1s to 10s and at most 524.2 MB.
    """

    images: typing.Optional[typing.List[InputGeminiOmniFlashImagesItem]] = pydantic.Field(default=None)
    """
    Reference images. 1 to 10 images, each at most 10.4 MB.
    """

    videos: typing.Optional[typing.List[InputGeminiOmniFlashVideosItem]] = pydantic.Field(default=None)
    """
    Reference videos. 1 to 3 videos, each at most 10s and at most 524.2 MB.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
