# This file was auto-generated by Fern from our API Definition.

import typing

InputGrokImagine20AspectRatio = typing.Union[
    typing.Literal["2:1", "20:9", "19.5:9", "16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16", "9:19.5", "9:20", "1:2"],
    typing.Any,
]
