# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_mai_image25aspect_ratio import InputMaiImage25AspectRatio
from .input_mai_image25images_item import InputMaiImage25ImagesItem
from .input_mai_image25output_format import InputMaiImage25OutputFormat
from .input_mai_image25quality import InputMaiImage25Quality


class InputMaiImage25(UniversalBaseModel):
    """
    Model-specific inputs for `mai-image-2-5`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, images, prompt
    (2) requires: aspect_ratio, prompt; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputMaiImage25AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    images: typing.Optional[typing.List[InputMaiImage25ImagesItem]] = pydantic.Field(default=None)
    """
    The single source image to edit.
    """

    output_format: typing.Optional[InputMaiImage25OutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    quality: InputMaiImage25Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
