# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_grok_video_aspect_ratio import InputGrokVideoAspectRatio
from .input_grok_video_resolution import InputGrokVideoResolution
from .input_grok_video_start_image import InputGrokVideoStartImage


class InputGrokVideo(UniversalBaseModel):
    """
    Model-specific inputs for `grok-video`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, prompt, resolution, start_image
    (2) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: start_image; accepts aspect_ratio: 16:9 | 4:3 | 3:2 | 1:1 | 2:3 | 3:4 | 9:16
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At most 4096 characters.
    """

    aspect_ratio: InputGrokVideoAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputGrokVideoResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputGrokVideoStartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video). At most 10.4 MB.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
