# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_topaz_video_upscaler_starlight_precise_reduce_sharpening import (
    InputTopazVideoUpscalerStarlightPreciseReduceSharpening,
)
from .input_topaz_video_upscaler_starlight_precise_resolution import InputTopazVideoUpscalerStarlightPreciseResolution
from .input_topaz_video_upscaler_starlight_precise_source_video import (
    InputTopazVideoUpscalerStarlightPreciseSourceVideo,
)


class InputTopazVideoUpscalerStarlightPrecise(UniversalBaseModel):
    """
    Model-specific inputs for `topaz-video-upscaler-starlight-precise`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    source_video: InputTopazVideoUpscalerStarlightPreciseSourceVideo = pydantic.Field()
    """
    The video to upscale. At most 300s and at most 524.2 MB.
    """

    resolution: InputTopazVideoUpscalerStarlightPreciseResolution = pydantic.Field()
    """
    Output resolution.
    """

    reduce_sharpening: typing.Optional[InputTopazVideoUpscalerStarlightPreciseReduceSharpening] = pydantic.Field(
        default=None
    )
    """
    How far to soften the diffusion pass, for sources the default sharpening renders harshly.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
