# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_seedream50lite_aspect_ratio import InputSeedream50LiteAspectRatio
from .input_seedream50lite_images_item import InputSeedream50LiteImagesItem
from .input_seedream50lite_resolution import InputSeedream50LiteResolution


class InputSeedream50Lite(UniversalBaseModel):
    """
    Model-specific inputs for `seedream-50-lite`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputSeedream50LiteAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputSeedream50LiteResolution = pydantic.Field()
    """
    Output resolution.
    """

    images: typing.Optional[typing.List[InputSeedream50LiteImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
