# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_reve21remix_aspect_ratio import InputReve21RemixAspectRatio
from .input_reve21remix_images_item import InputReve21RemixImagesItem
from .input_reve21remix_output_format import InputReve21RemixOutputFormat


class InputReve21Remix(UniversalBaseModel):
    """
    Model-specific inputs for `reve-21-remix`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputReve21RemixAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    images: typing.List[InputReve21RemixImagesItem] = pydantic.Field()
    """
    Images to edit or blend.
    """

    output_format: typing.Optional[InputReve21RemixOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
