# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_veed_video_background_removal_source_video import InputVeedVideoBackgroundRemovalSourceVideo


class InputVeedVideoBackgroundRemoval(UniversalBaseModel):
    """
    Model-specific inputs for `veed-video-background-removal`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    source_video: InputVeedVideoBackgroundRemovalSourceVideo = pydantic.Field()
    """
    Video whose background should be made transparent. At most 120s and at most 524.2 MB.
    """

    subject_is_person: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Optimize segmentation for a person rather than an object.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
