# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_kling_o1aspect_ratio import InputKlingO1AspectRatio
from .input_kling_o1end_image import InputKlingO1EndImage
from .input_kling_o1images_item import InputKlingO1ImagesItem
from .input_kling_o1resolution import InputKlingO1Resolution
from .input_kling_o1start_image import InputKlingO1StartImage


class InputKlingO1(UniversalBaseModel):
    """
    Model-specific inputs for `kling-o1`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, images, prompt
    (2) requires: aspect_ratio, duration_ms, prompt, start_image
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputKlingO1AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputKlingO1Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputKlingO1StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[InputKlingO1EndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    images: typing.Optional[typing.List[InputKlingO1ImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
