# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_gemini_omni_flash_aspect_ratio import InputGeminiOmniFlashAspectRatio
from .input_gemini_omni_flash_images_item import InputGeminiOmniFlashImagesItem
from .input_gemini_omni_flash_resolution import InputGeminiOmniFlashResolution
from .input_gemini_omni_flash_source_video import InputGeminiOmniFlashSourceVideo
from .input_gemini_omni_flash_start_image import InputGeminiOmniFlashStartImage
from .input_gemini_omni_flash_videos_item import InputGeminiOmniFlashVideosItem


class InputGeminiOmniFlash(UniversalBaseModel):
    """
    Model-specific inputs for `gemini-omni-flash`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputGeminiOmniFlashAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputGeminiOmniFlashResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputGeminiOmniFlashStartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    source_video: typing.Optional[InputGeminiOmniFlashSourceVideo] = pydantic.Field(default=None)
    """
    Source video (video-to-video).
    """

    images: typing.Optional[typing.List[InputGeminiOmniFlashImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    videos: typing.Optional[typing.List[InputGeminiOmniFlashVideosItem]] = pydantic.Field(default=None)
    """
    Reference videos.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
