# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_wan30aspect_ratio import InputWan30AspectRatio
from .input_wan30audios_item import InputWan30AudiosItem
from .input_wan30end_image import InputWan30EndImage
from .input_wan30images_item import InputWan30ImagesItem
from .input_wan30quality import InputWan30Quality
from .input_wan30resolution import InputWan30Resolution
from .input_wan30start_image import InputWan30StartImage
from .input_wan30videos_item import InputWan30VideosItem


class InputWan30(UniversalBaseModel):
    """
    Model-specific inputs for `wan-3-0`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, prompt, resolution, start_image; must omit: audios, images, videos
    (2) requires: aspect_ratio, duration_ms, images, prompt, resolution; must omit: end_image, start_image
    (3) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: audios, end_image, images, start_image, videos
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At most 5000 characters.
    """

    aspect_ratio: InputWan30AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputWan30Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    generate_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to generate native audio for the video.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed. From 0 to 2147483647.
    """

    start_image: typing.Optional[InputWan30StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video). At most 20 MB.
    """

    end_image: typing.Optional[InputWan30EndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video). At most 20 MB.
    """

    images: typing.Optional[typing.List[InputWan30ImagesItem]] = pydantic.Field(default=None)
    """
    Reference images. 1 to 10 images, each at most 20 MB.
    """

    videos: typing.Optional[typing.List[InputWan30VideosItem]] = pydantic.Field(default=None)
    """
    Reference videos. 1 to 5 videos, each at most 15s and at most 524.2 MB, at most 15s in total.
    """

    audios: typing.Optional[typing.List[InputWan30AudiosItem]] = pydantic.Field(default=None)
    """
    Reference audios. 1 to 5 audio files, each at most 15s and at most 104.8 MB, at most 15s in total.
    """

    quality: InputWan30Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
