# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_seedance20mini_aspect_ratio import InputSeedance20MiniAspectRatio
from .input_seedance20mini_audios_item import InputSeedance20MiniAudiosItem
from .input_seedance20mini_end_image import InputSeedance20MiniEndImage
from .input_seedance20mini_images_item import InputSeedance20MiniImagesItem
from .input_seedance20mini_resolution import InputSeedance20MiniResolution
from .input_seedance20mini_start_image import InputSeedance20MiniStartImage
from .input_seedance20mini_videos_item import InputSeedance20MiniVideosItem


class InputSeedance20Mini(UniversalBaseModel):
    """
    Model-specific inputs for `seedance-20-mini`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputSeedance20MiniAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputSeedance20MiniResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputSeedance20MiniStartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[InputSeedance20MiniEndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    images: typing.Optional[typing.List[InputSeedance20MiniImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    videos: typing.Optional[typing.List[InputSeedance20MiniVideosItem]] = pydantic.Field(default=None)
    """
    Reference videos.
    """

    audios: typing.Optional[typing.List[InputSeedance20MiniAudiosItem]] = pydantic.Field(default=None)
    """
    Reference audios.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
