# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_flux2max_aspect_ratio import InputFlux2MaxAspectRatio
from .input_flux2max_images_item import InputFlux2MaxImagesItem
from .input_flux2max_output_format import InputFlux2MaxOutputFormat


class InputFlux2Max(UniversalBaseModel):
    """
    Model-specific inputs for `flux2-max`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, images, prompt
    (2) requires: aspect_ratio, prompt; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputFlux2MaxAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    images: typing.Optional[typing.List[InputFlux2MaxImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend.
    """

    output_format: typing.Optional[InputFlux2MaxOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
