# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_minimax_hailuo23aspect_ratio import InputMinimaxHailuo23AspectRatio
from .input_minimax_hailuo23quality import InputMinimaxHailuo23Quality
from .input_minimax_hailuo23resolution import InputMinimaxHailuo23Resolution
from .input_minimax_hailuo23start_image import InputMinimaxHailuo23StartImage


class InputMinimaxHailuo23(UniversalBaseModel):
    """
    Model-specific inputs for `minimax-hailuo-23`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: typing.Optional[InputMinimaxHailuo23AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: typing.Optional[InputMinimaxHailuo23Resolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputMinimaxHailuo23StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    quality: InputMinimaxHailuo23Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
