# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_topaz_image_upscaler_face_recovery import InputTopazImageUpscalerFaceRecovery
from .input_topaz_image_upscaler_face_recovery_creativity import InputTopazImageUpscalerFaceRecoveryCreativity
from .input_topaz_image_upscaler_source_image import InputTopazImageUpscalerSourceImage
from .input_topaz_image_upscaler_target_resolution import InputTopazImageUpscalerTargetResolution


class InputTopazImageUpscaler(UniversalBaseModel):
    """
    Model-specific inputs for `topaz-image-upscaler`.
    """

    source_image: InputTopazImageUpscalerSourceImage = pydantic.Field()
    """
    The image to upscale. At most 30 MB.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    target_resolution: InputTopazImageUpscalerTargetResolution = pydantic.Field()
    """
    Short edge of the upscaled image. The long edge follows the source's aspect ratio.
    """

    face_recovery: typing.Optional[InputTopazImageUpscalerFaceRecovery] = pydantic.Field(default=None)
    """
    Restore facial detail, and how strongly. Off leaves faces to the general upscale.
    """

    face_recovery_creativity: typing.Optional[InputTopazImageUpscalerFaceRecoveryCreativity] = pydantic.Field(
        default=None
    )
    """
    How much a recovered face may be reimagined rather than reconstructed. Takes effect only with face_recovery on.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
