# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InputTopazImageUpscalerWonderSourceImage_Url(UniversalBaseModel):
    """
    The image to upscale. At most 30 MB.
    """

    source: typing.Literal["url"] = "url"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class InputTopazImageUpscalerWonderSourceImage_Asset(UniversalBaseModel):
    """
    The image to upscale. At most 30 MB.
    """

    source: typing.Literal["asset"] = "asset"
    asset_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


InputTopazImageUpscalerWonderSourceImage = typing_extensions.Annotated[
    typing.Union[InputTopazImageUpscalerWonderSourceImage_Url, InputTopazImageUpscalerWonderSourceImage_Asset],
    pydantic.Field(discriminator="source"),
]
