# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_minimax_h3max_camera_controls_camera_trajectory_item import (
    InputMinimaxH3MaxCameraControlsCameraTrajectoryItem,
)
from .input_minimax_h3max_camera_controls_resolution import InputMinimaxH3MaxCameraControlsResolution
from .input_minimax_h3max_camera_controls_start_image import InputMinimaxH3MaxCameraControlsStartImage


class InputMinimaxH3MaxCameraControls(UniversalBaseModel):
    """
    Model-specific inputs for `minimax-h3-max-camera-controls`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. From 1 to 7000 characters.
    """

    resolution: InputMinimaxH3MaxCameraControlsResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: InputMinimaxH3MaxCameraControlsStartImage = pydantic.Field()
    """
    Start frame. From 256px to 5760px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB.
    """

    camera_trajectory: typing.List[InputMinimaxH3MaxCameraControlsCameraTrajectoryItem] = pydantic.Field()
    """
    Camera path through the scene, as poses ordered by strictly increasing `time`. The first pose holds until its `time` and the last holds to the end of the clip; the camera interpolates between them. `time` runs 0 (start) to 1 (end), `azimuth` is the horizontal angle around the subject in degrees, `elevation` the vertical angle in degrees from -90 to 90, and `distance` the distance from the subject in scene units (above 0; 1 is where the input frame sits). Consecutive azimuths may travel at most 32 full turns in total. 2 to 12 items.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
