# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_gpt_image2aspect_ratio import InputGptImage2AspectRatio
from .input_gpt_image2images_item import InputGptImage2ImagesItem
from .input_gpt_image2output_format import InputGptImage2OutputFormat
from .input_gpt_image2quality import InputGptImage2Quality
from .input_gpt_image2resolution import InputGptImage2Resolution


class InputGptImage2(UniversalBaseModel):
    """
    Model-specific inputs for `gpt-image-2`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, images, prompt, resolution
    (2) requires: aspect_ratio, prompt, resolution; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At most 32000 characters.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Not available on this model. Its price is computed from the exact prompt submitted, which a rewrite would invalidate.
    """

    aspect_ratio: InputGptImage2AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputGptImage2Resolution = pydantic.Field()
    """
    Output resolution.
    """

    images: typing.Optional[typing.List[InputGptImage2ImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend. 1 to 16 images, each at most 30 MB.
    """

    output_format: typing.Optional[InputGptImage2OutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    quality: typing.Optional[InputGptImage2Quality] = pydantic.Field(default=None)
    """
    Quality level to generate at. `low` — the quickest and cheapest pass, for drafts, thumbnails, and rapid exploration. `medium` — balanced cost and fidelity, for everyday work and iterative refinement. `high` — the most rendering effort, for final deliverables and text-heavy designs.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
