# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_nano_banana2aspect_ratio import InputNanoBanana2AspectRatio
from .input_nano_banana2images_item import InputNanoBanana2ImagesItem
from .input_nano_banana2resolution import InputNanoBanana2Resolution


class InputNanoBanana2(UniversalBaseModel):
    """
    Model-specific inputs for `nano-banana-2`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputNanoBanana2AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputNanoBanana2Resolution = pydantic.Field()
    """
    Output resolution.
    """

    images: typing.Optional[typing.List[InputNanoBanana2ImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend, up to 14 in total (10 high-fidelity objects, 4 characters).
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
