# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_vidu_q3aspect_ratio import InputViduQ3AspectRatio
from .input_vidu_q3end_image import InputViduQ3EndImage
from .input_vidu_q3quality import InputViduQ3Quality
from .input_vidu_q3resolution import InputViduQ3Resolution
from .input_vidu_q3start_image import InputViduQ3StartImage


class InputViduQ3(UniversalBaseModel):
    """
    Model-specific inputs for `vidu-q3`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, duration_ms, prompt, resolution
    (2) requires: duration_ms, end_image, prompt, resolution, start_image
    (3) requires: duration_ms, prompt, resolution, start_image
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    aspect_ratio: typing.Optional[InputViduQ3AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: InputViduQ3Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputViduQ3StartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    end_image: typing.Optional[InputViduQ3EndImage] = pydantic.Field(default=None)
    """
    End frame (first-last-frame-to-video).
    """

    quality: InputViduQ3Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
