# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InputMinimaxSpeech25TurboPreview(UniversalBaseModel):
    """
    Model-specific inputs for `minimax-speech-25-turbo-preview`.
    """

    text: str = pydantic.Field()
    """
    Generation prompt. At most 9999 characters.
    """

    stability: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice stability. Higher values give a steadier, more consistent delivery; lower values allow more expressive variation between generations. From 0 to 1.
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech rate multiplier; 1.0 is the voice's natural pace. From 0.7 to 1.2.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code; 'auto' by default.
    """

    voice_id: str = pydantic.Field()
    """
    Voice to speak with (`voice_<uuid>`). List valid voices at GET /v3/models/minimax-speech-25-turbo-preview/voices.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
