# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_topaz_image_upscaler_transparency_source_image import InputTopazImageUpscalerTransparencySourceImage


class InputTopazImageUpscalerTransparency(UniversalBaseModel):
    """
    Model-specific inputs for `topaz-image-upscaler-transparency`.
    """

    source_image: InputTopazImageUpscalerTransparencySourceImage = pydantic.Field()
    """
    The image to upscale. At most 30 MB.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
