# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_minimax_h3max_aspect_ratio import InputMinimaxH3MaxAspectRatio
from .input_minimax_h3max_audios_item import InputMinimaxH3MaxAudiosItem
from .input_minimax_h3max_end_image import InputMinimaxH3MaxEndImage
from .input_minimax_h3max_images_item import InputMinimaxH3MaxImagesItem
from .input_minimax_h3max_resolution import InputMinimaxH3MaxResolution
from .input_minimax_h3max_start_image import InputMinimaxH3MaxStartImage
from .input_minimax_h3max_videos_item import InputMinimaxH3MaxVideosItem


class InputMinimaxH3Max(UniversalBaseModel):
    """
    Model-specific inputs for `minimax-h3-max`.

    Accepted field combinations (one per input mode):
    (1) requires: duration_ms, prompt, resolution, start_image; must omit: aspect_ratio, audios, end_image, images, videos
    (2) requires: duration_ms, end_image, prompt, resolution, start_image; must omit: aspect_ratio, audios, images, videos
    (3) requires: aspect_ratio, duration_ms, images, prompt, resolution; must omit: end_image, start_image
    (4) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: audios, end_image, images, start_image, videos; accepts aspect_ratio: 1:1 | 3:4 | 4:3 | 16:9 | 21:9 | 9:16
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. From 1 to 7000 characters.
    """

    resolution: InputMinimaxH3MaxResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    start_image: typing.Optional[InputMinimaxH3MaxStartImage] = pydantic.Field(default=None)
    """
    Start frame. From 256px to 5760px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB.
    """

    end_image: typing.Optional[InputMinimaxH3MaxEndImage] = pydantic.Field(default=None)
    """
    End frame. From 256px to 5760px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB.
    """

    aspect_ratio: typing.Optional[InputMinimaxH3MaxAspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio. Omitted or `adaptive` uses the supported ratio nearest the first reference image, else the first reference video.
    """

    images: typing.Optional[typing.List[InputMinimaxH3MaxImagesItem]] = pydantic.Field(default=None)
    """
    Reference images. 1 to 4 images, each from 256px to 1024px on each side, with an aspect ratio from 0.4 to 2.5, and at most 30 MB.
    """

    videos: typing.Optional[typing.List[InputMinimaxH3MaxVideosItem]] = pydantic.Field(default=None)
    """
    Reference videos. 1 to 3 videos, each from 2s to 15s and at most 524.2 MB, at most 15s in total.
    """

    audios: typing.Optional[typing.List[InputMinimaxH3MaxAudiosItem]] = pydantic.Field(default=None)
    """
    Reference audios. 1 to 3 audio files, each from 2s to 15s and at most 104.8 MB, at most 15s in total.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
