# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_wan27aspect_ratio import InputWan27AspectRatio
from .input_wan27end_image import InputWan27EndImage
from .input_wan27images_item import InputWan27ImagesItem
from .input_wan27resolution import InputWan27Resolution
from .input_wan27start_image import InputWan27StartImage


class InputWan27(UniversalBaseModel):
    """
    Model-specific inputs for `wan-2-7`.

    Accepted field combinations (one per input mode):
    (1) requires: duration_ms, prompt, resolution, start_image; must omit: aspect_ratio, images
    (2) requires: aspect_ratio, duration_ms, images, prompt, resolution; must omit: end_image, start_image; accepts duration_ms: 2000 | 3000 | 4000 | 5000 | 6000 | 7000 | 8000 | 9000 | 10000
    (3) requires: aspect_ratio, duration_ms, prompt, resolution; must omit: end_image, images, start_image
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At most 5000 characters.
    """

    negative_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    What to avoid in the generated video. At most 500 characters.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed. From 0 to 2147483647.
    """

    resolution: InputWan27Resolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputWan27StartImage] = pydantic.Field(default=None)
    """
    Start frame. At most 20 MB.
    """

    end_image: typing.Optional[InputWan27EndImage] = pydantic.Field(default=None)
    """
    End frame. At most 20 MB.
    """

    aspect_ratio: typing.Optional[InputWan27AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    images: typing.Optional[typing.List[InputWan27ImagesItem]] = pydantic.Field(default=None)
    """
    Reference images. 1 to 4 images, each at most 20 MB.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
