# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InputVeo31SourceVideo_Url(UniversalBaseModel):
    """
    Source video. From 1s to 30s and at most 524.2 MB.
    """

    source: typing.Literal["url"] = "url"
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class InputVeo31SourceVideo_Asset(UniversalBaseModel):
    """
    Source video. From 1s to 30s and at most 524.2 MB.
    """

    source: typing.Literal["asset"] = "asset"
    asset_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


InputVeo31SourceVideo = typing_extensions.Annotated[
    typing.Union[InputVeo31SourceVideo_Url, InputVeo31SourceVideo_Asset], pydantic.Field(discriminator="source")
]
