# This file was auto-generated by Fern from our API Definition.

import typing

from .input_hedra_character3audio_one_item import InputHedraCharacter3AudioOneItem
from .input_hedra_character3audio_zero import InputHedraCharacter3AudioZero

InputHedraCharacter3Audio = typing.Union[InputHedraCharacter3AudioZero, typing.List[InputHedraCharacter3AudioOneItem]]
