# This file was auto-generated by Fern from our API Definition.

import typing

InputNanoBanana2AspectRatio = typing.Union[
    typing.Literal[
        "adaptive", "16:9", "9:16", "1:1", "21:9", "4:3", "3:4", "3:2", "2:3", "5:4", "4:5", "1:4", "4:1", "1:8", "8:1"
    ],
    typing.Any,
]
