# This file was auto-generated by Fern from our API Definition.

import typing

from .input_hedra_avatar_audio_one_item import InputHedraAvatarAudioOneItem
from .input_hedra_avatar_audio_zero import InputHedraAvatarAudioZero

InputHedraAvatarAudio = typing.Union[InputHedraAvatarAudioZero, typing.List[InputHedraAvatarAudioOneItem]]
