# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InputElevenlabsMusic(UniversalBaseModel):
    """
    Model-specific inputs for `elevenlabs-music`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    duration_ms: int = pydantic.Field()
    """
    Length of the generated track, in milliseconds. Billed as whole seconds, rounded up. From 3000 to 600000.
    """

    lyrics: typing.Optional[str] = pydantic.Field(default=None)
    """
    Words for the track to sing. Sent to the provider inside the prompt, which reads lyrics from the prompt text and places them across the requested length. Cannot be combined with `force_instrumental`. At most 10000 characters.
    """

    force_instrumental: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Compose without vocals.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
