# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_kling_o3reference_images_item import InputKlingO3ReferenceImagesItem
from .input_kling_o3reference_resolution import InputKlingO3ReferenceResolution
from .input_kling_o3reference_source_video import InputKlingO3ReferenceSourceVideo


class InputKlingO3Reference(UniversalBaseModel):
    """
    Model-specific inputs for `kling-o3-reference`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    source_video: InputKlingO3ReferenceSourceVideo = pydantic.Field()
    """
    Source video (video-to-video).
    """

    images: typing.Optional[typing.List[InputKlingO3ReferenceImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    resolution: InputKlingO3ReferenceResolution = pydantic.Field()
    """
    Output resolution to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
