# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_flux2flex_aspect_ratio import InputFlux2FlexAspectRatio
from .input_flux2flex_images_item import InputFlux2FlexImagesItem
from .input_flux2flex_output_format import InputFlux2FlexOutputFormat


class InputFlux2Flex(UniversalBaseModel):
    """
    Model-specific inputs for `flux2-flex`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputFlux2FlexAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    images: typing.Optional[typing.List[InputFlux2FlexImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend.
    """

    output_format: typing.Optional[InputFlux2FlexOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    guidance: typing.Optional[float] = pydantic.Field(default=None)
    """
    How closely the model follows the prompt.
    """

    steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Denoising steps to run.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
