# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_gpt_image2aspect_ratio import InputGptImage2AspectRatio
from .input_gpt_image2images_item import InputGptImage2ImagesItem
from .input_gpt_image2output_format import InputGptImage2OutputFormat
from .input_gpt_image2quality import InputGptImage2Quality
from .input_gpt_image2resolution import InputGptImage2Resolution


class InputGptImage2(UniversalBaseModel):
    """
    Model-specific inputs for `gpt-image-2`.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = None
    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputGptImage2AspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputGptImage2Resolution = pydantic.Field()
    """
    Output resolution.
    """

    images: typing.Optional[typing.List[InputGptImage2ImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend.
    """

    output_format: typing.Optional[InputGptImage2OutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    quality: InputGptImage2Quality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
