# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_gpt_image25flare_aspect_ratio import InputGptImage25FlareAspectRatio
from .input_gpt_image25flare_images_item import InputGptImage25FlareImagesItem
from .input_gpt_image25flare_output_format import InputGptImage25FlareOutputFormat
from .input_gpt_image25flare_quality import InputGptImage25FlareQuality
from .input_gpt_image25flare_resolution import InputGptImage25FlareResolution


class InputGptImage25Flare(UniversalBaseModel):
    """
    Model-specific inputs for `gpt-image-2.5-flare`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, images, prompt, resolution
    (2) requires: aspect_ratio, prompt, resolution; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At most 32000 characters.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputGptImage25FlareAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputGptImage25FlareResolution = pydantic.Field()
    """
    Output resolution.
    """

    output_format: typing.Optional[InputGptImage25FlareOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    images: typing.Optional[typing.List[InputGptImage25FlareImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend. 1 to 16 images, each at most 30 MB.
    """

    quality: typing.Optional[InputGptImage25FlareQuality] = pydantic.Field(default=None)
    """
    Quality level to generate at. `auto` — automatically selects rendering quality for the prompt. `low` — low rendering quality for the Flare model. `medium` — medium rendering quality for the Flare model. `high` — high rendering quality for the Flare model.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
