# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_omnihuman15aspect_ratio import InputOmnihuman15AspectRatio
from .input_omnihuman15audio import InputOmnihuman15Audio
from .input_omnihuman15resolution import InputOmnihuman15Resolution
from .input_omnihuman15start_image import InputOmnihuman15StartImage


class InputOmnihuman15(UniversalBaseModel):
    """
    Model-specific inputs for `omnihuman-15`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generation prompt.
    """

    aspect_ratio: typing.Optional[InputOmnihuman15AspectRatio] = pydantic.Field(default=None)
    """
    Output aspect ratio.
    """

    resolution: InputOmnihuman15Resolution = pydantic.Field()
    """
    Output resolution.
    """

    start_image: InputOmnihuman15StartImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    audio: InputOmnihuman15Audio = pydantic.Field()
    """
    Driving audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
