# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_kling_v3motion_control_character_orientation import InputKlingV3MotionControlCharacterOrientation
from .input_kling_v3motion_control_resolution import InputKlingV3MotionControlResolution
from .input_kling_v3motion_control_source_video import InputKlingV3MotionControlSourceVideo
from .input_kling_v3motion_control_start_image import InputKlingV3MotionControlStartImage


class InputKlingV3MotionControl(UniversalBaseModel):
    """
    Model-specific inputs for `kling-v3-motion-control`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Generation prompt.
    """

    character_orientation: typing.Optional[InputKlingV3MotionControlCharacterOrientation] = pydantic.Field(default=None)
    """
    Whether the output character's orientation follows the reference video ('video' — better for complex motion) or the character image ('image' — better for camera movement). Also caps the source video: 30s for 'video', 10s for 'image'.
    """

    start_image: InputKlingV3MotionControlStartImage = pydantic.Field()
    """
    Start frame (image-to-video).
    """

    source_video: InputKlingV3MotionControlSourceVideo = pydantic.Field()
    """
    Source video (video-to-video).
    """

    resolution: InputKlingV3MotionControlResolution = pydantic.Field()
    """
    Output resolution to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
