# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_hedra_avatar_aspect_ratio import InputHedraAvatarAspectRatio
from .input_hedra_avatar_audio import InputHedraAvatarAudio
from .input_hedra_avatar_bounding_box_target import InputHedraAvatarBoundingBoxTarget
from .input_hedra_avatar_resolution import InputHedraAvatarResolution
from .input_hedra_avatar_start_image import InputHedraAvatarStartImage


class InputHedraAvatar(UniversalBaseModel):
    """
    Model-specific inputs for `hedra-avatar`.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputHedraAvatarAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputHedraAvatarResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration in ms. At most 600000.
    """

    start_image: InputHedraAvatarStartImage = pydantic.Field()
    """
    Start frame (image-to-video). At most 10.4 MB.
    """

    audio: InputHedraAvatarAudio = pydantic.Field()
    """
    Driving audio: a single reference, or a list of references for multi-speaker generation — one audio per speaker, played in list order. 1 to 4 audio files, each from 0.5s to 600s and at most 104.8 MB.
    """

    bounding_box_target: typing.Optional[InputHedraAvatarBoundingBoxTarget] = pydantic.Field(default=None)
    """
    Speaker position(s) in the start frame, as normalized [x, y] image coordinates (0-1 from the top-left).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
