# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_seedream50lite_aspect_ratio import InputSeedream50LiteAspectRatio
from .input_seedream50lite_images_item import InputSeedream50LiteImagesItem
from .input_seedream50lite_output_format import InputSeedream50LiteOutputFormat
from .input_seedream50lite_resolution import InputSeedream50LiteResolution


class InputSeedream50Lite(UniversalBaseModel):
    """
    Model-specific inputs for `seedream-50-lite`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, images, prompt, resolution
    (2) requires: aspect_ratio, prompt, resolution; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputSeedream50LiteAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputSeedream50LiteResolution = pydantic.Field()
    """
    Output resolution.
    """

    output_format: typing.Optional[InputSeedream50LiteOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    images: typing.Optional[typing.List[InputSeedream50LiteImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend. 1 to 14 images, each at most 30 MB.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
