# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_hidream_o1image_aspect_ratio import InputHidreamO1ImageAspectRatio
from .input_hidream_o1image_images_item import InputHidreamO1ImageImagesItem
from .input_hidream_o1image_output_format import InputHidreamO1ImageOutputFormat
from .input_hidream_o1image_quality import InputHidreamO1ImageQuality
from .input_hidream_o1image_resolution import InputHidreamO1ImageResolution


class InputHidreamO1Image(UniversalBaseModel):
    """
    Model-specific inputs for `hidream-o1-image`.

    Accepted field combinations (one per input mode):
    (1) requires: aspect_ratio, images, prompt; must omit: resolution
    (2) requires: aspect_ratio, prompt, resolution; must omit: images
    """

    prompt: str = pydantic.Field()
    """
    Generation prompt. At least 1 character.
    """

    num_outputs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of outputs generated per job. Only 1 is supported.
    """

    enhance_prompt: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Rewrite the prompt before generation. An LLM expands it into a fuller description and the model receives that text instead of the submitted one; the result's `prompt` reports what ran.
    """

    aspect_ratio: InputHidreamO1ImageAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    images: typing.Optional[typing.List[InputHidreamO1ImageImagesItem]] = pydantic.Field(default=None)
    """
    Images to edit or blend. 1 to 10 images, each at most 30 MB.
    """

    output_format: typing.Optional[InputHidreamO1ImageOutputFormat] = pydantic.Field(default=None)
    """
    Output image format.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    guidance_scale: typing.Optional[float] = pydantic.Field(default=None)
    """
    How closely the model follows the prompt. From 0 to 20.
    """

    num_inference_steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Denoising steps to run. From 1 to 50.
    """

    resolution: typing.Optional[InputHidreamO1ImageResolution] = pydantic.Field(default=None)
    """
    Output resolution.
    """

    quality: InputHidreamO1ImageQuality = pydantic.Field()
    """
    Quality level to generate at.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
