# This file was auto-generated by Fern from our API Definition.

import typing

InputHappyHorseAspectRatio = typing.Union[
    typing.Literal["21:9", "16:10", "16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16", "10:16", "9:21"], typing.Any
]
