# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .input_happy_horse_aspect_ratio import InputHappyHorseAspectRatio
from .input_happy_horse_images_item import InputHappyHorseImagesItem
from .input_happy_horse_resolution import InputHappyHorseResolution
from .input_happy_horse_start_image import InputHappyHorseStartImage


class InputHappyHorse(UniversalBaseModel):
    """
    Model-specific inputs for `happy-horse`.
    """

    num_outputs: typing.Optional[int] = None
    prompt: str = pydantic.Field()
    """
    Generation prompt.
    """

    aspect_ratio: InputHappyHorseAspectRatio = pydantic.Field()
    """
    Output aspect ratio.
    """

    resolution: InputHappyHorseResolution = pydantic.Field()
    """
    Output resolution.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration in ms.
    """

    start_image: typing.Optional[InputHappyHorseStartImage] = pydantic.Field(default=None)
    """
    Start frame (image-to-video).
    """

    images: typing.Optional[typing.List[InputHappyHorseImagesItem]] = pydantic.Field(default=None)
    """
    Reference images.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed for reproducible output; omit for a random seed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
