# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .job_log_event import JobLogEvent
from .job_log_level import JobLogLevel
from .job_log_source import JobLogSource


class JobLogItem(UniversalBaseModel):
    """
    One customer-visible lifecycle event for a v3 job.
    """

    id: int
    timestamp: dt.datetime
    level: JobLogLevel
    event: JobLogEvent
    message: str
    source: JobLogSource
    data: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
