# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .api_key_kind import ApiKeyKind


class KeyCreateResponse(UniversalBaseModel):
    key_id: str = pydantic.Field()
    """
    The key's public identifier.
    """

    credential: str = pydantic.Field()
    """
    The full `<key_id>:<secret>` pair — a valid Bearer credential. Returned exactly once, at creation; store it now.
    """

    kind: ApiKeyKind
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label for the key.
    """

    scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Scopes granted to the key; null means full access (a legacy key predating scopes).
    """

    workspace_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The workspace the key bills and acts in.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO-8601 instant the key stops authenticating; null means it never expires.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO-8601 instant the key was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
