# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .api_key_kind import ApiKeyKind


class KeyRotateResponse(UniversalBaseModel):
    key_id: str
    credential: str
    kind: ApiKeyKind
    name: typing.Optional[str] = None
    scopes: typing.Optional[typing.List[str]] = None
    workspace_id: typing.Optional[str] = None
    expires_at: typing.Optional[str] = None
    previous_secret_expires_at: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
