# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LlmPricing(UniversalBaseModel):
    """
    Price per one million tokens, in USD.
    """

    usd_per1m_input_tokens: typing_extensions.Annotated[
        float, FieldMetadata(alias="usd_per_1m_input_tokens"), pydantic.Field(alias="usd_per_1m_input_tokens")
    ]
    usd_per1m_output_tokens: typing_extensions.Annotated[
        float, FieldMetadata(alias="usd_per_1m_output_tokens"), pydantic.Field(alias="usd_per_1m_output_tokens")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
