# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LlmCapabilitiesObject(UniversalBaseModel):
    """
    What this model accepts and returns.
    """

    tools: bool
    response_format: bool
    vision: bool
    reasoning: bool
    sampling_parameters: typing.List[str]
    reasoning_efforts: typing.List[str]
    response_format_types: typing.List[str]
    parallel_tool_calls: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
