# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_envelope import ErrorEnvelope
from .log_drain_format import LogDrainFormat


class LogDrainConfig(UniversalBaseModel):
    id: str
    name: str
    url: str
    format: LogDrainFormat
    header_names: typing.Optional[typing.List[str]] = None
    enabled: bool
    batch_size: int
    consecutive_failures: int
    last_success_at: typing.Optional[dt.datetime] = None
    last_failure_at: typing.Optional[dt.datetime] = None
    last_failure_status: typing.Optional[int] = None
    last_error: typing.Optional[ErrorEnvelope] = pydantic.Field(default=None)
    """
    Why the most recent batch delivery failed, in the same error envelope `GET /jobs/{job_id}` returns for a failed job: a stable `code` from the shared error vocabulary, a fixed operator-facing `message`, and `retryable`. Null while no batch has failed, and cleared on the next success. Destination URLs, headers, credentials, response bodies, and internal exception text are never included. Nor is your drain URL written to Hedra's own logs, since it may carry authentication in its query string. `retryable` describes the condition, not what Hedra did: every failed batch is requeued until the drain auto-disables, so it answers whether fixing the destination and re-enabling is likely to help. Drains that last failed before this field became structured report `UNKNOWN`.
    """

    disabled_reason: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    updated_by_key_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
