# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .log_drain_format import LogDrainFormat


class LogDrainConfig(UniversalBaseModel):
    id: str
    name: str
    url: str
    format: LogDrainFormat
    header_names: typing.Optional[typing.List[str]] = None
    enabled: bool
    batch_size: int
    consecutive_failures: int
    last_success_at: typing.Optional[str] = None
    last_failure_at: typing.Optional[str] = None
    last_failure_status: typing.Optional[int] = None
    last_error: typing.Optional[str] = None
    disabled_reason: typing.Optional[str] = None
    created_at: str
    updated_at: str
    updated_by_key_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
