# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LogDrainTestResponse(UniversalBaseModel):
    ok: bool = pydantic.Field()
    """
    Whether the test batch got a 2xx from the endpoint.
    """

    response_status: typing.Optional[int] = pydantic.Field(default=None)
    """
    HTTP status the endpoint returned; null when the request never got a response.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why the test failed; null on success.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
