# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_envelope import ErrorEnvelope
from .output_status import OutputStatus


class OutputItem(UniversalBaseModel):
    """
    One item of a job's `outputs[]` (`GET /v3/jobs/{job_id}`). `outputs` is
    always an array, even for a single output.

    Every key is always present. The ones a modality carries no value for
    serialize as null — an image output reports `duration_ms: null` and
    `fps: null`, an audio output `width: null` — so the shape is one object
    rather than one per modality.
    """

    status: typing.Optional[OutputStatus] = None
    url: typing.Optional[str] = None
    content_type: typing.Optional[str] = None
    width: typing.Optional[int] = None
    height: typing.Optional[int] = None
    duration_ms: typing.Optional[int] = None
    fps: typing.Optional[int] = None
    error: typing.Optional[ErrorEnvelope] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
