# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .generation import Generation
from .page_info import PageInfo


class PagedResponseGeneration(UniversalBaseModel):
    page_info: PageInfo = pydantic.Field()
    """
    Paging information.
    """

    data: typing.List[Generation] = pydantic.Field()
    """
    Page data.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(PagedResponseGeneration)
