# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .request_log_emitter import RequestLogEmitter
from .request_log_event import RequestLogEvent
from .request_log_level import RequestLogLevel


class RequestLogItem(UniversalBaseModel):
    """
    One customer-visible lifecycle event for a v3 request.
    """

    id: int
    timestamp: dt.datetime
    level: RequestLogLevel
    event: RequestLogEvent
    message: str
    source: RequestLogEmitter
    data: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
