# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .request_status import RequestStatus
from .status_log import StatusLog


class StatusResponse(UniversalBaseModel):
    request_id: str
    status: RequestStatus
    progress: typing.Optional[float] = None
    estimated_completion_at: typing.Optional[str] = None
    logs: typing.Optional[typing.List[StatusLog]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
