# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .job_status import JobStatus


class SubmitResponse(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    This job's id (`job_<uuid>`). The job's output asset carries the same UUID, so once the job completes, replacing the `job_` prefix with `asset_` yields the `asset_id` to reference its output in a later submit's media inputs.
    """

    model: str
    status: JobStatus
    status_url: str = pydantic.Field()
    """
    Path of this job's status monitor: poll GET /v3/jobs/{job_id}/status for status, progress, and an estimate.
    """

    result_url: str = pydantic.Field()
    """
    Path of the job resource itself: GET /v3/jobs/{job_id} returns the result envelope, including the outputs once it completes. Also the value of this response's `Location` header.
    """

    estimated_completion_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO-8601 instant this job is estimated to finish. Null when no estimate exists for the model yet; poll GET /v3/jobs/{job_id}/status for a refreshed one.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
