# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .job_status import JobStatus


class SubmitResponse(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    This job's id — server-issued, and opaque.
    """

    model: str = pydantic.Field()
    """
    The resolved model id this job runs on.
    """

    status: JobStatus
    status_url: str = pydantic.Field()
    """
    Path of this job's status monitor: poll GET /v3/jobs/{job_id}/status for status, progress, and the estimated completion time.
    """

    result_url: str = pydantic.Field()
    """
    Path of the job resource itself: GET /v3/jobs/{job_id} returns the result envelope, including the outputs once it completes. Also the value of this response's `Location` header.
    """

    estimated_completion_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO-8601 instant this job is estimated to finish, as of this response. Null when no estimate is available yet, and when the job has already finished. The estimate can change while the job runs: poll `GET /v3/jobs/{job_id}/status` for the current one.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
