# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TransactionLlmUsage(UniversalBaseModel):
    """
    The chat requests an `llm_usage` transaction sums.
    """

    model: str = pydantic.Field()
    """
    The model the requests used.
    """

    request_count: int = pydantic.Field()
    """
    How many requests the row sums.
    """

    period_start: dt.datetime = pydantic.Field()
    """
    Start of the UTC day the row covers. A request counts toward the day it was created, even when it was charged after midnight. `GET /v3/usage/llm` lists your own requests in the row when given this as `start`, `period_end` as `end`, and `model`.
    """

    period_end: dt.datetime = pydantic.Field()
    """
    End of the UTC day the row covers, exclusive: one day after `period_start`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
