# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UsageBucket(UniversalBaseModel):
    """
    One usage rollup row. `key` is ``"total"`` for the summary, an ISO date
    (``YYYY-MM-DD``, UTC) for ``group_by=day``, or a clean model id for
    ``group_by=model``.
    """

    key: str
    requests: int
    credits_spent: int
    usd_spent: typing.Optional[float] = pydantic.Field(default=None)
    """
    Net spend in USD, derived from usd_micros_spent.
    """

    usd_micros_spent: typing.Optional[int] = pydantic.Field(default=None)
    """
    Net spend in integer micro-dollars (1e-6 USD). Legacy credit-only rows use the canonical credits-to-USD conversion.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
