# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UsageBucket(UniversalBaseModel):
    """
    One usage rollup row. `key` is ``"total"`` for the summary, an ISO date
    (``YYYY-MM-DD``, UTC) for ``group_by=day``, or a public model id for
    ``group_by=model``.
    """

    key: str = pydantic.Field()
    """
    What this bucket rolls up: `"total"`, an ISO date (`YYYY-MM-DD`, UTC), or a public model id — per `group_by`.
    """

    jobs: int = pydantic.Field()
    """
    Jobs submitted in this bucket.
    """

    requests: typing.Optional[int] = pydantic.Field(default=None)
    """
    Settled LLM chat requests in this bucket. Unlike `jobs` (which counts submits, charged or not), this counts requests whose usage settled — a request refused before any work never appears, and a late settlement lands in the window the request was created in.
    """

    spent: float = pydantic.Field()
    """
    Net amount spent in this bucket.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
