# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VoiceSummary(UniversalBaseModel):
    """
    One voice a model accepts; `id` goes into ``input.voice_id`` on submit.
    """

    id: str = pydantic.Field()
    """
    The voice's id (`voice_<uuid>`); pass it as `input.voice_id` on submit.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable name.
    """

    preview_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of a short audio sample of this voice.
    """

    labels: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Curation metadata (language, gender, accent, ...).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
