# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_envelope import ErrorEnvelope
from .job_status import JobStatus
from .metrics import Metrics
from .output_item import OutputItem


class WebhookPayload(UniversalBaseModel):
    """
    Body of a webhook delivery: the `GET /jobs/{job_id}` result envelope without its poll-only fields (`logs`, `cost`, `currency`) — poll the job to read those.
    """

    job_id: str
    model: str
    quality: typing.Optional[str] = pydantic.Field(default=None)
    """
    The quality level this job ran at; present only for models that offer quality levels.
    """

    status: JobStatus
    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    The prompt this job ran with. When `enhance_prompt` was set, this is the rewritten prompt the model received rather than the one submitted. Absent on models that take no prompt.
    """

    outputs: typing.Optional[typing.List[OutputItem]] = None
    metrics: typing.Optional[Metrics] = pydantic.Field(default=None)
    """
    Timing for this job; present on completed jobs only.
    """

    error: typing.Optional[ErrorEnvelope] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
