# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_delivery_status import WebhookDeliveryStatus


class WebhookDeliverySummary(UniversalBaseModel):
    request_id: str
    request_accessible: bool
    model: str
    event_type: typing.Optional[str] = None
    status: WebhookDeliveryStatus
    source: str
    attempts: int
    last_response_status: typing.Optional[int] = None
    last_error: typing.Optional[str] = None
    webhook_url: str
    created_at: str
    last_attempt_at: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
