# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.job_log_item import JobLogItem
from ...types.status_response import StatusResponse

JobsStreamResponse = typing.Union[StatusResponse, JobLogItem]
