# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key_scope import ApiKeyScope
from ..types.token_create_response import TokenCreateResponse
from .raw_client import AsyncRawTokensClient, RawTokensClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TokensClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTokensClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTokensClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTokensClient
        """
        return self._raw_client

    def create(
        self,
        *,
        ttl_seconds: typing.Optional[int] = OMIT,
        scopes: typing.Optional[typing.Sequence[ApiKeyScope]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TokenCreateResponse:
        """
        Parameters
        ----------
        ttl_seconds : typing.Optional[int]

        scopes : typing.Optional[typing.Sequence[ApiKeyScope]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TokenCreateResponse
            Successful Response

        Examples
        --------
        from hedra import Hedra

        client = Hedra(
            api_key="YOUR_API_KEY",
        )
        client.tokens.create()
        """
        _response = self._raw_client.create(ttl_seconds=ttl_seconds, scopes=scopes, request_options=request_options)
        return _response.data


class AsyncTokensClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTokensClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTokensClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTokensClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        ttl_seconds: typing.Optional[int] = OMIT,
        scopes: typing.Optional[typing.Sequence[ApiKeyScope]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TokenCreateResponse:
        """
        Parameters
        ----------
        ttl_seconds : typing.Optional[int]

        scopes : typing.Optional[typing.Sequence[ApiKeyScope]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TokenCreateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from hedra import AsyncHedra

        client = AsyncHedra(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tokens.create()


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            ttl_seconds=ttl_seconds, scopes=scopes, request_options=request_options
        )
        return _response.data
